app/private/models.py
from datetime import datetime
from .. import db

class File(db.Model):
    __tablename__ = 'files'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id', ondelete='CASCADE'), nullable=False)
    user_email = db.Column(db.String(256), nullable=False)
    title = db.Column(db.String(256), nullable=False)
    created = db.Column(db.DateTime, default=datetime.now())
    file_name = db.Column(db.String())
    description = db.Column(db.Text)
    size = db.Column(db.Integer)
    hash = db.Column(db.String(256), nullable=False)

    def __repr__(self):
        return f'<File {self.title}>'

    def save(self):
        if not self.id:
            db.session.add(self)
            db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    @staticmethod
    def get_all():
        return File.query.all()

    @staticmethod
    def get_by_id(id):
        return File.query.get(id)

    @staticmethod
    def get_by_hash(hash):
        return File.query.filter_by(hash=hash).first()

    @staticmethod
    def get_by_user(user_id):
        return File.query.filter_by(user_id=user_id).all()

app/private/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileRequired
from wtforms import FileField, SubmitField, TextAreaField, StringField
from wtforms.validators import Length


class FileForm(FlaskForm):
    title = StringField('Title', validators=[Length(max=128)])
    description = TextAreaField('Description')
    file = FileField('File', validators=[FileRequired(message='Please select a file.'), FileAllowed(['jpeg', 'jpg', 'png', 'txt', 'doc', 'csv', 'pdf'],
                                                                     'Unsupported file type (supported: JPEG, JPG, PNG, TXT, DOC, CSV, PDF)')])
    submit = SubmitField('Upload')

app/private/__init__.py
from flask import Blueprint

private_bp = Blueprint('private', __name__, template_folder='private/templates/admin')

from . import routes

app/private/routes.py
import os
from flask import current_app, render_template, redirect, url_for, send_from_directory, flash, abort
from flask_login import login_required, current_user
from .forms import FileForm
from .models import File
from . import private_bp
from werkzeug.exceptions import RequestEntityTooLarge
from werkzeug.utils import secure_filename
import hashlib


def pretty_files(files):
    for file in files:
        file.created = file.created.strftime("%Y-%m-%d %H:%M:%S")
        if round(int(file.size) / 1024, 2) >= 1:
            file.size = str(round(int(file.size) / 1024 / 1024, 2)) + ' Mb'
        else:
            file.size = str(round(int(file.size) / 1024, 2)) + ' Kb'
    return files


@private_bp.route('/my_files')
@login_required
def my_files():
    files = pretty_files(File.get_by_user(current_user.id))
    return render_template('private/my_files.html', name=current_user.first_name, files=files)


@private_bp.route('/all_files')
@login_required
def all_files():
    files = pretty_files(File.get_all())
    return render_template('private/all_files.html', name=current_user.first_name, files=files)


@private_bp.route('/download_file/<path:file_hash>')
@login_required
def download_file(file_hash):
    file_name = File.get_by_hash(file_hash).file_name
    return send_from_directory(directory=current_app.config['FILES_DIR'], filename=file_name, as_attachment=True)


@private_bp.route('/profile')
@login_required
def profile():
    return render_template('private/profile.html', name=current_user.first_name)


@private_bp.route('/upload_file', methods=['GET', 'POST'])
@login_required
def upload_file():
    #try:
    #    form = FileForm()
    #except RequestEntityTooLarge as e:
    #    abort(413)
    form = FileForm()
    if form.validate_on_submit():
        if os.path.splitext(form.file.data.filename)[1] not in current_app.config['UPLOAD_EXTENSIONS']:
            abort(413)
        file = form.file.data
        if file:
            title = form.title.data
            description = form.description.data
            file_name = secure_filename(file.filename)
            files_dir = current_app.config['FILES_DIR']
            blob = file.read()
            # Solución "chapucera" que comentaba en __init__.py #
            if len(blob) > 16 * 1024 * 1024:
                flash('File too large (max. 16Mb')
                return render_template('private/upload-file.html', form=form)
            ####################################################
            hash_key = hashlib.sha256(blob).hexdigest()
            if File.get_by_hash(hash_key) is not None:
                flash('This file already exists in the server.')
                return render_template('private/upload-file.html', form=form)
            file.seek(0)
            os.makedirs(files_dir, exist_ok=True)
            file_path = os.path.join(files_dir, file_name)
            file.save(file_path)

            file = File(
                user_id=current_user.id,
                user_email=current_user.email,
                title=title,
                file_name=file_name,
                description=description,
                size=len(blob),
                hash=hash_key)

            file.save()

            return redirect(url_for('private.my_files'))

    return render_template('private/upload-file.html', form=form)

app/templates/private/all_files.html
{% extends "base-site.html" %}

{% block content %}
<h1 class="title">
All files:
</h1>

  <table id="data_table" class="compact hover row-border" style="width:100%; color: black;">
    <thead>
      <tr>
        <th>File name</th>
        <th>Size</th>
        <th>Hash</th>
        <th>Owner</th>
        <th>Created date</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for file in files %}
        <tr>
          <td>{{file.file_name}}</td>
          <td>{{file.size}}</td>
          <td>{{file.hash}}</td>
          <td>{{file.user_email}}</td>
          <td>{{file.created}}</td>
          <td><a href="{{ url_for('private.download_file', file_hash=file.hash) }}">Download</a></td>
          <td>{% if current_user.is_admin %}<a href="{{ url_for('admin.delete_entry', access='user', item='file', entry_id=file.id) }}">Delete</a>{% endif %}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

app/templates/private/my_files.html
{% extends "base-site.html" %}

{% block content %}
<h1 class="title">
  {{ name }} - My files:

</h1>

  <table id="data_table" class="compact hover row-border" style="width:100%; color: black;">
    <thead>
      <tr>
        <th>File name</th>
        <th>Size</th>
        <th>Hash</th>
        <th>Owner</th>
        <th>Created date</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for file in files %}
        <tr>
          <td>{{file.file_name}}</td>
          <td>{{file.size}}</td>
          <td>{{file.hash}}</td>
          <td>{{file.user_email}}</td>
          <td>{{file.created}}</td>
          <td><a href="{{ url_for('private.download_file', file_hash=file.hash) }}">Download</a></td>
          <td>{% if current_user.is_admin %}<a href="{{ url_for('admin.delete_entry', access='user', item='file', entry_id=file.id) }}">Delete</a>{% endif %}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

app/templates/private/profile.html
{% extends "base-site.html" %}

{% block content %}
<h1 class="title">
  Welcome, {{ name }}!
</h1>
{% endblock %}

app/templates/private/upload-file.html
{% extends "base-site.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Upload Files</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}
        {% from "_formmacro.html" import render_field, render_submit %}
        <form method=post enctype="multipart/form-data">
            {{ form.hidden_tag() }}
        <dl>
            {{ render_field(form.title, placeholder="File Title (optional)", class="input is-large") }}
            {{ render_field(form.description, placeholder="File Description (optional)", class="input is-large") }}
        <br>
        <div>
            {{ render_field(form.file, class="is-large") }}
        </div>
        <br>
        </dl>
        <p>{{ render_submit(form.submit, class="button is-block is-info is-large is-fullwidth") }}
        </form>
    </div>
</div>
{% endblock %}